#!/usr/bin/env python3
"""Generate the compact 14x24 Cyrillic LCD font used by HackyLens."""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
FONT_CANDIDATES = (
    Path("C:/Windows/Fonts/DejaVuSansMono.ttf"),
    Path("C:/Windows/Fonts/consola.ttf"),
)
CODEPOINTS = [0x0401, *range(0x0410, 0x0450), 0x0451]
WIDTH = 14
HEIGHT = 24
ROW_BYTES = 2


def render_glyph(font: ImageFont.FreeTypeFont, codepoint: int) -> bytes:
    image = Image.new("1", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    character = chr(codepoint)
    left, top, right, bottom = draw.textbbox((0, 0), character, font=font)
    x = (WIDTH - (right - left)) // 2 - left
    y = (HEIGHT - (bottom - top)) // 2 - top
    draw.text((x, y), character, font=font, fill=1)
    output = bytearray()
    for row in range(HEIGHT):
        bits = 0
        for column in range(WIDTH):
            if image.getpixel((column, row)):
                bits |= 1 << (15 - column)
        output.extend((bits >> 8, bits & 0xFF))
    return bytes(output)


def main() -> None:
    font_path = next((path for path in FONT_CANDIDATES if path.is_file()), None)
    if font_path is None:
        raise SystemExit("No Cyrillic monospace font found")
    font = ImageFont.truetype(str(font_path), 20)
    data = b"".join(render_glyph(font, codepoint) for codepoint in CODEPOINTS)
    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "/* Generated by tools/make_cyrillic_font.py. */",
        "#define HACKYLENS_CYRILLIC_YO_UPPER 0x0401U",
        "#define HACKYLENS_CYRILLIC_FIRST 0x0410U",
        "#define HACKYLENS_CYRILLIC_LAST 0x044FU",
        "#define HACKYLENS_CYRILLIC_YO_LOWER 0x0451U",
        f"#define HACKYLENS_CYRILLIC_COUNT {len(CODEPOINTS)}U",
        "",
        "static const uint8_t g_hackylens_font_cyrillic_1bpp[] = {",
    ]
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    lines.extend(("};", ""))
    output = ROOT / "firmware/assets/hackylens_font_cyrillic_1bpp.h"
    output.write_text("\n".join(lines), encoding="ascii")
    print(output)


if __name__ == "__main__":
    main()
