#ifndef HK_FILES_IMAGE_CONFIG_H
#define HK_FILES_IMAGE_CONFIG_H

#define PHOTO_VIEW_MAX_W 1600U
#define PHOTO_VIEW_MAX_H 1200U
#define PHOTO_ROW_MAX_BYTES (PHOTO_VIEW_MAX_W * 3U)
#define PHOTO_BMP565_HEADER_SIZE 66U
#define PHOTO_PPM_HEADER_MAX 32U

#define PNG_COMP_MAX (512U * 1024U)
#define PNG_OUT_MAX (640U * 480U * 2U)
#define HUFF_TABLE_BITS 15U
#define HUFF_TABLE_SIZE (1U << HUFF_TABLE_BITS)
#define HUFF_INVALID 0xFFFFU

#endif
