#ifndef HK_APRILTAG_CONFIG_H
#define HK_APRILTAG_CONFIG_H

#define APRILTAG_INPUT_W 160U
#define APRILTAG_INPUT_H 120U
#define APRILTAG_MAX_HAMMING 1
#define APRILTAG_QUAD_DECIMATE 2.0f
#define APRILTAG_MIN_CLUSTER_PIXELS 24
#define APRILTAG_REFINE_EDGES 0
#define APRILTAG_FAMILY_ID_COUNT 587U
#define APRILTAG_SELECTED_BYTES ((APRILTAG_FAMILY_ID_COUNT + 7U) / 8U)
#define APRILTAG_SETTINGS_SCHEMA 0xA7U
#define APRILTAG_SETTINGS_ROW_COUNT 9U
#define APRILTAG_SETTINGS_REFINE 0U
#define APRILTAG_SETTINGS_OUTPUT 1U
#define APRILTAG_SETTINGS_CLEAR_IDS 2U
#define APRILTAG_SETTINGS_FPS 3U
#define APRILTAG_SETTINGS_LIGHT 4U
#define APRILTAG_SETTINGS_RGB_RED 5U
#define APRILTAG_SETTINGS_RGB_GREEN 6U
#define APRILTAG_SETTINGS_RGB_BLUE 7U
#define APRILTAG_SETTINGS_VERSION 8U
#define APRILTAG_DISPLAY_HOLD_MISSES 1U
#define APRILTAG_WORKER_IDLE_MS 1U
#define APRILTAG_START_TIMEOUT_US 1000000ULL

#endif
