#ifndef HK_MICROPYTHON_APP_CONFIG_H
#define HK_MICROPYTHON_APP_CONFIG_H

#include "../../core/hk_app.h"

#define HK_MICROPYTHON_SCREEN SCREEN_APP_SLOT_2
#define MICROPYTHON_LIST_VISIBLE_ROWS 7U
#define MICROPYTHON_ACTION_COUNT 5U
#define MICROPYTHON_PREVIEW_LINES 9U
#define MICROPYTHON_PREVIEW_COLUMNS 19U
#define MICROPYTHON_LOG_HISTORY_LINES 48U
#define MICROPYTHON_LOG_VISIBLE_LINES 9U
#define MICROPYTHON_LOG_COLUMNS 25U
#define MICROPYTHON_STATUS_COLUMNS 25U
#define MICROPYTHON_LIST_REFRESH_TICKS 200U
#define MICROPYTHON_RENDER_TICKS 5U
#define MICROPYTHON_CONSOLE_RENDER_TICKS 20U
#define MICROPYTHON_PREVIEW_READ_CHUNK 128U

#endif
