#ifndef HK_OBJECT_DETECT_CONFIG_H
#define HK_OBJECT_DETECT_CONFIG_H

#include "../../config/settings_config.h"

#define OBJECT_DETECT_INPUT_W 320U
#define OBJECT_DETECT_INPUT_H 240U
#define OBJECT_DETECT_INPUT_BYTES (OBJECT_DETECT_INPUT_W * OBJECT_DETECT_INPUT_H * 3U)
#define OBJECT_DETECT_GRID_W 10U
#define OBJECT_DETECT_GRID_H 7U
#define OBJECT_DETECT_GRID_CELLS (OBJECT_DETECT_GRID_W * OBJECT_DETECT_GRID_H)
#define OBJECT_DETECT_ANCHOR_COUNT 5U
#define OBJECT_DETECT_CLASS_COUNT 20U
#define OBJECT_DETECT_CHANNELS \
    (OBJECT_DETECT_ANCHOR_COUNT * (OBJECT_DETECT_CLASS_COUNT + 5U))
#define OBJECT_DETECT_OUTPUT_BYTES \
    (OBJECT_DETECT_CHANNELS * OBJECT_DETECT_GRID_CELLS * sizeof(float))
#define OBJECT_DETECT_CANDIDATE_MAX \
    (OBJECT_DETECT_ANCHOR_COUNT * OBJECT_DETECT_GRID_CELLS)
#define OBJECT_DETECT_RESULT_MAX 8U

#define DRISTY_KMODELS_ROOT "/dristy.kmodels"
#define DRISTY_KMODELS_LEGACY "/dristy.kmodels"

#define OBJECT_DETECT_MODEL_DIRECTORY DRISTY_KMODELS_ROOT "/object20"
#define OBJECT_DETECT_MODEL_PATH DRISTY_KMODELS_ROOT "/object20/model.kmodel"
#define OBJECT_DETECT_MANIFEST_PATH DRISTY_KMODELS_ROOT "/object20/manifest.hkai"
#define OBJECT_DETECT_LABELS_PATH DRISTY_KMODELS_ROOT "/object20/labels.txt"

#define OBJECT_DETECT_MODEL_DIRECTORY_LEGACY DRISTY_KMODELS_LEGACY "/object20"
#define OBJECT_DETECT_MODEL_PATH_LEGACY DRISTY_KMODELS_LEGACY "/object20/model.kmodel"
#define OBJECT_DETECT_MANIFEST_PATH_LEGACY DRISTY_KMODELS_LEGACY "/object20/manifest.hkai"
#define OBJECT_DETECT_LABELS_PATH_LEGACY DRISTY_KMODELS_LEGACY "/object20/labels.txt"
#define OBJECT_DETECT_MODEL_MAX_BYTES (2U * 1024U * 1024U)
#define OBJECT_DETECT_UNLOAD_TIMEOUT_US 2000000ULL

#define OBJECT_DETECT_DEFAULT_CONFIDENCE 50U
#define OBJECT_DETECT_DEFAULT_NMS 20U
#define OBJECT_DETECT_DISPLAY_HOLD_MISSES 4U

#define OBJECT_DETECT_SETTINGS_OFFSET SETTINGS_APP_DATA_V2_SIZE
#define OBJECT_DETECT_SETTINGS_BYTES 8U
#define OBJECT_DETECT_SETTINGS_SCHEMA 0xD2U

#define OBJECT_DETECT_SETTINGS_ROW_COUNT 8U
#define OBJECT_DETECT_SETTINGS_CONFIDENCE 0U
#define OBJECT_DETECT_SETTINGS_NMS 1U
#define OBJECT_DETECT_SETTINGS_FPS 2U
#define OBJECT_DETECT_SETTINGS_LIGHT 3U
#define OBJECT_DETECT_SETTINGS_RGB_RED 4U
#define OBJECT_DETECT_SETTINGS_RGB_GREEN 5U
#define OBJECT_DETECT_SETTINGS_RGB_BLUE 6U
#define OBJECT_DETECT_SETTINGS_VERSION 7U

_Static_assert(OBJECT_DETECT_SETTINGS_OFFSET + OBJECT_DETECT_SETTINGS_BYTES <=
               SETTINGS_APP_DATA_SIZE,
               "Object Detection settings exceed shared app-data allocation");

#endif
