#ifndef HK_FACE_DETECT_CONFIG_H
#define HK_FACE_DETECT_CONFIG_H

#define DRISTY_FACE_KMODELS_ROOT "/dristy.kmodels"
#define DRISTY_FACE_KMODELS_LEGACY "/hackylens.kmodels"

#define FACE_DETECT_MODEL_DIRECTORY DRISTY_FACE_KMODELS_ROOT
#define FACE_DETECT_MODEL_PATH DRISTY_FACE_KMODELS_ROOT "/detect.kmodel"

#define FACE_DETECT_MODEL_DIRECTORY_LEGACY DRISTY_FACE_KMODELS_LEGACY
#define FACE_DETECT_MODEL_PATH_LEGACY DRISTY_FACE_KMODELS_LEGACY "/detect.kmodel"

#define FACE_DETECT_UNLOAD_TIMEOUT_US 2000000ULL

#endif
