#ifndef HK_SETTINGS_MENU_LAYOUT_H
#define HK_SETTINGS_MENU_LAYOUT_H

#define SETTINGS_MENU_ROW_Y0 58
#define SETTINGS_MENU_ROW_H 36
#define SETTINGS_MENU_VISIBLE_ROWS 4
#define SETTINGS_MENU_VALUE_SIZE 24
#define SETTINGS_MENU_REPEAT_INITIAL_TICKS 12
#define SETTINGS_MENU_REPEAT_NEXT_TICKS 4

#endif
