#ifndef HK_SETTINGS_CONFIG_H
#define HK_SETTINGS_CONFIG_H

#include "flash_layout.h"

#define SETTINGS_SAVE_DELAY_TICKS 25
#define SETTINGS_FLASH_SLOT0 HK_FLASH_PARTITION_SETTINGS_0_OFFSET
#define SETTINGS_FLASH_SLOT1 HK_FLASH_PARTITION_SETTINGS_1_OFFSET
#define SETTINGS_FLASH_SLOT_SIZE HK_FLASH_PARTITION_SETTINGS_0_SIZE
#define SETTINGS_MAGIC 0x484B5331UL
#define SETTINGS_STORAGE_VERSION 4U
#define SETTINGS_STORAGE_V3_VERSION 3U
#define SETTINGS_STORAGE_V2_VERSION 2U
#define SETTINGS_STORAGE_LEGACY_VERSION 1U
#define SETTINGS_AUTOSTART_V3_COUNT 9U
#define SETTINGS_APP_DATA_V2_SIZE 80U
#define SETTINGS_APP_DATA_SIZE 88U
#define SETTINGS_RGB_MARK 0xC3U
#define SETTINGS_FPS_MARK 0xF5U
#define SETTINGS_CAMERA_MARK_V1 0xA5U
#define SETTINGS_CAMERA_MARK 0xA6U
#define SETTINGS_FPS_MARK_LOW (SETTINGS_FPS_MARK & 0x0FU)
#define SETTINGS_PAYLOAD_AUTO_SLEEP_MASK 0x1FU
#define SETTINGS_PAYLOAD_FEATURE_SHIFT 5U
#define SETTINGS_FEATURE_FLAGS_MASK 0x07U
#define SETTINGS_EXTERNAL_LINK_I2C_FLAG 0x02U
#define SETTINGS_UART_SPEED_SHIFT 1U
#define SETTINGS_UART_SPEED_MASK 0x06U
#define SETTINGS_UART_SPEED_MARK 0x08U
#define SETTINGS_QR_DECODE_RATE_DEFAULT 5U
#define SETTINGS_QR_DECODE_RATE_MIN 1U
#define SETTINGS_QR_DECODE_RATE_MAX 5U

#endif
