#!/usr/bin/env python3
"""Generate Dristy UI 1bpp fonts: 14x24 body + 10x16 caption (Iosevka / Roboto Mono)."""

from __future__ import annotations

import subprocess
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "firmware" / "assets" / "dristy_font_1bpp.h"
FIRST = 32
LAST = 126


def fc_match(pattern: str) -> Path | None:
    try:
        proc = subprocess.run(
            ["fc-match", pattern, "-f", "%{file}\n"],
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError:
        return None
    if proc.returncode != 0 or not proc.stdout.strip():
        return None
    path = Path(proc.stdout.strip())
    return path if path.is_file() else None


def pick_font() -> Path:
    for pattern in (
        "Iosevka Nerd Font Mono",
        "Iosevka",
        "Roboto Mono",
        "DejaVu Sans Mono",
    ):
        path = fc_match(pattern)
        if path:
            print(f"[dristy-font] using {path}")
            return path
    raise SystemExit("No Iosevka/Roboto Mono/DejaVu Sans Mono font found (install ttf)")


def render_glyph(
    font: ImageFont.FreeTypeFont, codepoint: int, width: int, height: int
) -> bytes:
    image = Image.new("1", (width, height), 0)
    draw = ImageDraw.Draw(image)
    character = chr(codepoint)
    left, top, right, bottom = draw.textbbox((0, 0), character, font=font)
    x = (width - (right - left)) // 2 - left
    y = (height - (bottom - top)) // 2 - top
    draw.text((x, y), character, font=font, fill=1)
    output = bytearray()
    for row in range(height):
        bits = 0
        for column in range(width):
            if image.getpixel((column, row)):
                bits |= 1 << (15 - column)
        output.extend((bits >> 8, bits & 0xFF))
    return bytes(output)


def emit_array(name: str, data: bytes) -> list[str]:
    lines = [f"static const uint8_t {name}[] = {{"]
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    lines.append("};")
    return lines


def main() -> None:
    font_path = pick_font()
    body_font = ImageFont.truetype(str(font_path), 18)
    small_font = ImageFont.truetype(str(font_path), 12)
    body_w, body_h, body_rb = 14, 24, 2
    small_w, small_h, small_rb = 10, 16, 2
    body = b"".join(
        render_glyph(body_font, cp, body_w, body_h) for cp in range(FIRST, LAST + 1)
    )
    small = b"".join(
        render_glyph(small_font, cp, small_w, small_h) for cp in range(FIRST, LAST + 1)
    )
    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"/* Generated by tools/make_dristy_font.py from {font_path.name} */",
        f"#define DRISTY_FONT_FIRST {FIRST}",
        f"#define DRISTY_FONT_LAST {LAST}",
        f"#define DRISTY_FONT_COUNT {LAST - FIRST + 1}",
        f"#define DRISTY_FONT_W {body_w}",
        f"#define DRISTY_FONT_H {body_h}",
        f"#define DRISTY_FONT_ROW_BYTES {body_rb}",
        "",
        *emit_array("g_dristy_font_1bpp", body),
        "",
        f"#define DRISTY_FONT_SMALL_W {small_w}",
        f"#define DRISTY_FONT_SMALL_H {small_h}",
        f"#define DRISTY_FONT_SMALL_ROW_BYTES {small_rb}",
        "",
        *emit_array("g_dristy_font_small_1bpp", small),
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="ascii")
    print(OUT)


if __name__ == "__main__":
    main()
