#ifndef HK_TERMINAL_CONFIG_H
#define HK_TERMINAL_CONFIG_H

#include "../../core/hk_app.h"

#define HK_TERMINAL_SCREEN SCREEN_APP_SLOT_1

#define TERMINAL_HISTORY_LINE_COUNT 64U
#define TERMINAL_HISTORY_LINE_LENGTH 192U

#define TERMINAL_NORMAL_SCALE 1U
#define TERMINAL_SMALL_SCALE 2U

#define TERMINAL_REPEAT_INITIAL_TICKS 15U
#define TERMINAL_REPEAT_NEXT_TICKS 3U
#define TERMINAL_OK_HOLD_TICKS 40U

#define TERMINAL_SETTINGS_FONT_SMALL_FLAG 0x01U

#endif
